In [28]:
import pandas as pd

In [29]:
n1 = pd.read_csv("negativity_analysis_dataset/n1.csv")
n5 = pd.read_csv("negativity_analysis_dataset/n5.csv")

In [30]:
n1.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [31]:
n5.columns

Index(['Consumer_complaint', 'Product', 'Sentiment', 'Priority'], dtype='object')

In [32]:
n1 = n1.rename(columns={"comment_text": "text"})
n5 = n5.rename(columns={"Consumer_complaint": "text"})

In [33]:
n1.head(2)

,id,text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0

In [34]:
n5.head(2)

,text,Product,Sentiment,Priority
0,I had overdraft protection with Regions Bank i...,Checking or savings account or service,0,1
1,"I am the sole, legal representative of my dece...",Checking or savings account or service,0,1

In [35]:
n1.drop("id" , axis = 1 , inplace = True)

In [36]:
n1["severity"] = (n1["toxic"] + n1["severe_toxic"] + n1["obscene"] + n1["threat"] +n1["insult"] + n1["identity_hate"])

In [37]:
sentiment_map = {
    "Negative": 3,
    "Neutral": 1,
    "Positive": 0
}

priority_map = {
    "High": 3,
    "Medium": 2,
    "Low": 1
}

n5["severity"] = n5["Sentiment"].map(sentiment_map) + n5["Priority"].map(priority_map)

In [38]:
n1 = n1[["text", "severity"]]
n5 = n5[["text", "severity"]]

In [39]:
data = pd.concat([n1, n5], ignore_index=True)

In [41]:
data[data["severity"] == 6]

                                                     text  severity
1017    WOULDN'T BE THE FIRST TIME BITCH. FUCK YOU I'L...       6.0
1312    SHUT UP, YOU FAT POOP, OR I WILL KICK YOUR ASS!!!       6.0
7299    You're a stupid cunt \n\nFuck you dumb arse, y...       6.0
13648   Bitch \n\nYou are a little bitch. I fuckin spe...       6.0
13964   I am going to murder ZimZalaBim ST47 for being...       6.0
22158   FUCK YOU!!!!!!!!!!!! YOU FUCKING NIGGER BAG OF...       6.0
29968   u motherfukkin bitch i want to rape you smelly...       6.0
32098   Fuck All Asyriac Nation \n\nQamishli belong to...       6.0
33951   GO FUCK YOURSELF BITCH.  I HATE YOUR SOULD.  M...       6.0
38513   AM GOING TO RAPE YOU IN THE ASS YOU FAT BITCH ...       6.0
38578   fuck you honkey, why you hatin' on blacks? You...       6.0
46155         So fuck off and die, rape fantasising sluts       6.0
55160   ANYONE WHO SUPPORTS THIS IS FUCKING SICK. MEN ...       6.0
59279   JEW \n\nGet the fuck out of here you jewish so...       6.0
65075   FAGGOTS!  YO FUCKER IT WAS FUCKING HAYES YOU F...       6.0
67247   YOURE A FRREAKING JEW, AND PLEAZE COMMIT SUICIDE.       6.0
73821   Shut up you asswipe, we don't care. I'll decap...       6.0
77139   Eat shit you fucking arse rapping jew fucking ...       6.0
80612   I hit a jack off all day, after the rape my mo...       6.0
82141   Help! \n\nIf you become an admin, I will fucki...       6.0
99819   Glenn Beck is a faggot. He likes dick in his a...       6.0
100222  Urgent!!!! \n\nMind yo own fucken buisiness st...       6.0
106617  , I hope your retarded kids get anal raped and...       6.0
116767  Go fuck yourself!!! you fucking delteted it an...       6.0
118928  You god damn son of a bitch you fucking blocke...       6.0
123794  She is a Motherfucker \n\nI will block you Mot...       6.0
133551  and your little faggot boy Propol, pray, pray ...       6.0
142513  faggot \n\nYou lil piece of shit I haven’t van...       6.0
151131  LGBT \n\nyou little fuck , are you a fag , tha...       6.0
157428  Ok.... \n\nBitch i swear to God i will fuckin ...       6.0
159400  Shalom \n\nSemite, get the fuck out of here. I...       6.0

In [44]:
len(data)

161321

In [45]:
data["severity"].value_counts()

severity
0.0    143346
1.0      6360
3.0      4209
2.0      3480
4.0      1760
5.0       385
6.0        31
Name: count, dtype: int64

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=20000,   stop_words="english", ngram_range=(1,2) )

In [47]:
data["severity"].isna().sum()

np.int64(1750)

In [48]:
data = data.dropna(subset=["severity"])

In [49]:
x = vectorizer.fit_transform(data["text"])
y = data["severity"]

In [50]:
x.shape , y.shape

((159571, 20000), (159571,))

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=19,stratify=y)

## Ridge Regression

In [53]:
from sklearn.linear_model import Ridge
m1 = Ridge(alpha = 1)
m1.fit(x_train, y_train)

Ridge(alpha=1)

In [54]:
y_pred = m1.predict(x_test)

In [55]:
from sklearn.metrics import mean_absolute_error
mae_1 = mean_absolute_error(y_test, y_pred)
print("MAE m1:", mae_1)

MAE m1: 0.20611280767546264

In [57]:
import  numpy as np

In [58]:
y_pred_m1_round = np.clip(np.round(y_pred),0,6)

## LinearSVR

In [59]:
from sklearn.svm import LinearSVR
m2 = LinearSVR()
m2.fit(x_train,y_train)
pred = m2.predict(x_test)

In [61]:
from sklearn.metrics import mean_absolute_error
mae_m2 = mean_absolute_error(y_test, pred)
print("MAE m2:", mae_m2)

MAE m2: 0.12831982848791879

## we will use linearsvr

In [62]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    "C": [0.1, 0.5, 1, 2, 5],
    "epsilon": [0.0, 0.1, 0.2],
    "loss": ["epsilon_insensitive", "squared_epsilon_insensitive"]
}

In [64]:
grid = GridSearchCV(
    m2,
    param_grid,
    cv=3,
    scoring="neg_mean_absolute_error",
    n_jobs=-1
)

grid.fit(x_train, y_train)

C:\Users\divyadarshee dash\AppData\Roaming\Python\Python313\site-packages\sklearn\svm\_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

GridSearchCV(cv=3, estimator=LinearSVR(), n_jobs=-1,
             param_grid={'C': [0.1, 0.5, 1, 2, 5], 'epsilon': [0.0, 0.1, 0.2],
                         'loss': ['epsilon_insensitive',
                                  'squared_epsilon_insensitive']},
             scoring='neg_mean_absolute_error')

In [65]:
best_model = grid.best_estimator_

In [67]:
pred = best_model.predict(x_test)
print("Tuned MAE:", mean_absolute_error(y_test, pred))

Tuned MAE: 0.12828075559533075

In [68]:
import joblib
joblib.dump(best_model, "severity_model_linearsvr.joblib")
joblib.dump(vectorizer, "severity_model_vectorizer.joblib")

['severity_model_vectorizer.joblib']

In [21]:
import joblib

In [22]:
v = joblib.load("severity_model_vectorizer.joblib")
m = joblib.load("severity_model_linearsvr.joblib")

In [23]:
def r(Text):
    x_vec = v.transform([Text])
    y_pred = m.predict(x_vec)
    return int(y_pred[0])

In [43]:
print(r(""))

2